version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: product_management_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: product_management
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - product_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: product_management_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_NAME: product_management
      DB_USERNAME: root
      DB_PASSWORD: password123
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      NODE_ENV: production
      PORT: 3000
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - product_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api-docs", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:

networks:
  product_network:
    driver: bridge